development: &default
  adapter: mysql2
  database: airaware_dev
  pool: 25
  timeout: 5000
  encoding: utf8

staging:
  <<: *default

production:
  <<: *default

test: &test
  <<: *default
  database: airaware_test
  pool: 5
  timeout: 5000
