# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency:  25
:queues:
  - [default, 10]

staging:
  :pidfile: /var/www/airaware/shared/pids/sidekiq.pid

production:
  :pidfile: /var/www/airaware/shared/pids/sidekiq.pid
